### ISSUE TITLE
Connecting to an account ? more ideas~

### ISSUE THREAD

**Issue by HeartBtz** [LetrixZ/faccina#23]
Hi :) 
 
First of all, is it normal that account management doesn't work yet? Or is it only on my instance? 

Then I have a few ideas for you when the accounts will be operational:
-Do you plan to create a kind of reading history? (for example, we'll know where we are in our reading e.g. page135/345) as well as a history of what we've already read? 
-What about bookmarking projects for later reading?
-A choice of the number of doujins per page would be a good thing :)
-The possibility of making collections, even if it goes back to the idea of bookmarking.

beyond that, thank you for your work, it's very nice, and quite useful to me!

**Comment by LetrixZ** [comment]
Hi.

There isn't any account managment yet as I still need to define what to show, aside from password and email.

The reading history is a good idea. I'll also see to add a page limit setting.

I'm planning on adding user collections. That would solve the bookmarks.

**Comment by HeartBtz** [comment]
I'm waiting for it ! don't hesitate to send me testing environments :)

Small detail, even if it's not important, there's a bug in BUN. It has trouble reading archives when these are on a partition (linux) other than the executable. This leads to problems when scanning resources. 
To bypass this, I had to create a 1TB virtual disk on my proxmox, and that's pretty impractical I must admit haha, I'd have preferred to be able to mount NFS, but Bun doesn't support it very well, sad! 
https://github.com/oven-sh/bun/issues/7412

I'll let you know about any bugs I see as soon as I find them, don't hesitate :)

**Comment by LetrixZ** [comment]
On macOS, I'm using a NFS mount for the content directory. Didn't try SMB yet.

I'll try that later.

**Comment by HeartBtz** [comment]
During my tests, I was indeed on an NFS mount on my Debian.
As soon as I changed the source of my archives, the problem was solved.

**Comment by LetrixZ** [comment]
Added configuration for page limit options and user collections to the lastest version.

Now I'm working on the reading history.

**Comment by HeartBtz** [comment]
Thanks a lot !! :D

**Comment by LetrixZ** [comment]
Reading history is done.
I'll add a way to remove from history later and maybe add toggle to disable it as an user.

**Comment by HeartBtz** [comment]
Hello :D 

I don't have any history on latest version x)

**Comment by LetrixZ** [comment]
> Hello :D
> 
> I don't have any history on latest version x)

It should appear there in the user menu

<img width="198" alt="image" src="https://github.com/user-attachments/assets/13789aec-1164-451b-96ad-9e0b44dabf4a">

**Comment by LetrixZ** [comment]
I found an error there

**Comment by HeartBtz** [comment]
![image](https://github.com/user-attachments/assets/19680902-7a13-4226-89db-b97aff1c2d49)
Oops, i forgot to do another "bun install & bun run build".... sorry.....
