### ISSUE TITLE
Small adding with default_sort in config.toml

### ISSUE THREAD

**Issue by HeartBtz** [LetrixZ/faccina#29]
I promise it's the last one for today: 

can you add "random" in config.toml for loading random pages ? 

`"message": "Invalid enum value. Expected 'released_at' | 'created_at' | 'title' | 'pages', received 'random'"`

Thanks :D

**Comment by LetrixZ** [comment]
Added in 44de827

It should apply to every listing that isn't favorites or a collection since these already have their default order, saved at and gallery order respectively.
