### ISSUE TITLE
Indexing: Faccina fails to recognize external metadata files now

### ISSUE THREAD

**Issue by WiseMan6** [LetrixZ/faccina#33]
The file structure:
```
[Sasachinn] More! Intruder x2 (Comic Bavel 2024-08).cbz
[Sasachinn] More! Intruder x2 (Comic Bavel 2024-08).yaml
```
[Metadata file](https://github.com/ccdc06/metadata/blob/master/hentainexus.com_17001-18000/%5BSasachinn%5D%20More!%20Intruder%20x2%20(Comic%20Bavel%202024-08).yaml)

However, running `bun cli index` only gets me this far:
![Pasted image 20241217123546](https://github.com/user-attachments/assets/fef04b4f-12c4-4ecf-976c-5519d12c4239)

I haven't been around for two weeks, so I have no idea what broke it and when. All I can say is that it works just fine on [#e641142](https://github.com/LetrixZ/faccina/commit/e6411424f907217d5271bc306e70efb96774c55c) and earlier.

**Comment by LetrixZ** [comment]
Fixed in 80acfe1
